### ISSUE TITLE
Fdroid: useless permission + update url

### ISSUE THREAD

**Issue by bagage** [SoupeauCaillou/heriswap#1]
Change Fdroid repository URL to this, and remove Google Play permission which is not needed.

**Comment by MazeChaZer** [comment]
I just created a merge request in the official F-Droid repository to fix the broken links:
https://gitlab.com/fdroid/fdroiddata/merge_requests/419

**Comment by bagage** [comment]
Thanks!

**Comment by MazeChaZer** [comment]
The merge request has been accepted.
